test workflow

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -46,33 +46,33 @@ jobs:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
 
-      - name: Wait for localhost:3000 to become available
-        run: |
-          make start-server &
-          echo "Waiting for localhost:3000 to become available..."
-          attempt=1
-          max_attempts=3
-          while [ $attempt -le $max_attempts ]; do
-              echo "Attempt $attempt of $max_attempts"
-              if $(curl --output /dev/null --silent --head --fail http://localhost:3000); then
-                  echo "localhost:3000 is now available."
-                  break
-              fi
-              attempt=$((attempt+1))
-              sleep 5
-          done
-          if [ $attempt -gt $max_attempts ]; then
-              echo "Failed to connect to localhost:3000 after $max_attempts attempts."
-              exit 1
-          fi
-        env:
-          POSTGRES_PORT: 5432
-          POSTGRES_HOST: localhost
-          POSTGRES_DATABASE: postgres
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          JWT_SECRET: 6b23439e8fee67c5da38b61b8779e9f41a5e3e36efe723c6299dd2111896def6
-          ADMIN_PASSWORD: 123123
+      # - name: Wait for localhost:3000 to become available
+      #   run: |
+      #     make start-server &
+      #     echo "Waiting for localhost:3000 to become available..."
+      #     attempt=1
+      #     max_attempts=3
+      #     while [ $attempt -le $max_attempts ]; do
+      #         echo "Attempt $attempt of $max_attempts"
+      #         if $(curl --output /dev/null --silent --head --fail http://localhost:3000); then
+      #             echo "localhost:3000 is now available."
+      #             break
+      #         fi
+      #         attempt=$((attempt+1))
+      #         sleep 5
+      #     done
+      #     if [ $attempt -gt $max_attempts ]; then
+      #         echo "Failed to connect to localhost:3000 after $max_attempts attempts."
+      #         exit 1
+      #     fi
+      #   env:
+      #     POSTGRES_PORT: 5432
+      #     POSTGRES_HOST: localhost
+      #     POSTGRES_DATABASE: postgres
+      #     POSTGRES_USER: postgres
+      #     POSTGRES_PASSWORD: postgres
+      #     JWT_SECRET: 6b23439e8fee67c5da38b61b8779e9f41a5e3e36efe723c6299dd2111896def6
+      #     ADMIN_PASSWORD: 123123
 
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
